// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksLink = {
  /**
   * Link
   */
  link:
    | {
        /**
         * Selected
         */
        _selected: "internal";

        /**
         * Internal
         */
        internal: {
          /**
           * Internal link
           */
          internalLink: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "external";

        /**
         * External
         */
        external: {
          /**
           * External link
           */
          externalLink: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "none";

        /**
         * None
         */
        none: Record<string, unknown>;
      };
};
