// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type SiteConfig = XP.SiteConfig;

declare global {
  namespace XP {
    interface SiteConfig {
      /**
       * The organizations logo
       */
      logoId?: string;

      /**
       * Column
       */
      footerColumns?: Array<string> | string;

      /**
       * Title
       */
      errorTitle?: string;

      /**
       * Error Message
       */
      errorMessage?: string;

      /**
       * Image
       */
      errorImage?: string;
    }
  }
}
