// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksText = {
  /**
   * Title
   */
  title?: string;

  /**
   * Text
   */
  text?: string;
};
