// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ArticleHeader = import("./article-header").ArticleHeader;

declare global {
  interface XpPartMap {
    "no.item.starter:article-header": ArticleHeader;
  }
}
