// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ArticleHeader = import("./article-header").ArticleHeader;
export type BlocksView = import("./blocks-view").BlocksView;
export type ContentList = import("./content-list").ContentList;

declare global {
  interface XpPartMap {
    "no.item.starter:article-header": ArticleHeader;
    "no.item.starter:blocks-view": BlocksView;
    "no.item.starter:content-list": ContentList;
  }
}
