// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type ContentList = import("./content-list").ContentList;
export type SimpleHeader = import("./simple-header").SimpleHeader;

declare global {
  interface XpPartMap {
    "no.item.starter:content-list": ContentList;
    "no.item.starter:simple-header": SimpleHeader;
  }
}
