// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Intro = import("./intro").Intro

declare global {
  interface XpXData {
    "no-item-starter"?: {
      intro?: Intro;
    }
  }
}
