// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Intro = import("./intro").Intro
export type MenuItem = import("./menu-item").MenuItem

declare global {
  interface XpXData {
    "no-item-starter"?: {
      intro?: Intro;
      "menu-item"?: MenuItem;
    }
  }
}
