// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type MenuItem = {
  /**
   * Show in menu?
   */
  menuItem: boolean;

  /**
   * Override menu name
   */
  menuName?: string;
};
