// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Article = import("./article").Article;

declare global {
  namespace XP {
    interface ContentTypes {
      "no.item.starter:article": Article;
    }
  }
}
