// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Blocks = {
  /**
   * Content blocks
   */
  blocks?: Array<
    | {
        /**
         * Selected
         */
        _selected: "blocks-text";

        /**
         * Text
         */
        "blocks-text": {
          /**
           * Title
           */
          title?: string;

          /**
           * Text
           */
          text?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-images";

        /**
         * Images
         */
        "blocks-images": {
          /**
           * Image
           */
          items: Array<{
            /**
             * Image
             */
            imageId: string;

            /**
             * Description of the image for visually impaired users (alt text)
             */
            altText: string;

            /**
             * Caption
             */
            caption?: string;
          }>;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-factbox";

        /**
         * Factbox
         */
        "blocks-factbox": {
          /**
           * Title
           */
          title?: string;

          /**
           * Text
           */
          text: string;

          /**
           * Theme
           */
          theme?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-accordion";

        /**
         * Accordion
         */
        "blocks-accordion": {
          /**
           * Title
           */
          title?: string;

          /**
           * Theme
           */
          theme?: string;

          /**
           * Accordion element
           */
          items: Array<{
            /**
             * Title
             */
            title: string;

            /**
             * Text
             */
            text: string;
          }>;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-cards";

        /**
         * Cards
         */
        "blocks-cards": {
          /**
           * Title
           */
          title?: string;

          /**
           * Theme
           */
          theme?: string;

          /**
           * Image placement
           */
          imageClass: "blocks-card--image-left" | "blocks-card--image-right" | "blocks-card--image-top" | "blocks-card--image-bottom";

          /**
           * Column count
           */
          columnsClass: "blocks-card--cols-1" | "blocks-card--cols-2" | "blocks-card--cols-3";

          /**
           * Cards
           */
          items: Array<{
            /**
             * Title
             */
            title?: string;

            /**
             * Link
             */
            link:
              | {
                  /**
                   * Selected
                   */
                  _selected: "internal";

                  /**
                   * Internal
                   */
                  internal: {
                    /**
                     * Internal link
                     */
                    internalLink: string;
                  };
                }
              | {
                  /**
                   * Selected
                   */
                  _selected: "external";

                  /**
                   * External
                   */
                  external: {
                    /**
                     * External link
                     */
                    externalLink: string;
                  };
                }
              | {
                  /**
                   * Selected
                   */
                  _selected: "none";

                  /**
                   * None
                   */
                  none: Record<string, unknown>;
                };

            /**
             * Kicker
             */
            kicker?: string;

            /**
             * Text
             */
            text?: string;

            /**
             * Image
             */
            imageId?: string;
          }>;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-quote";

        /**
         * Quote
         */
        "blocks-quote": {
          /**
           * Text
           */
          text: string;

          /**
           * Name of person quoted
           */
          author?: string;

          /**
           * Author Image
           */
          imageId?: string;

          /**
           * Title
           */
          publicationTitle?: string;

          /**
           * Url
           */
          publicationUrl?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-reuse";

        /**
         * Reuse
         */
        "blocks-reuse": {
          /**
           * Include blocks from this content
           */
          contentId: string;
        };
      }
  >;

  /**
   * Vertical spacing
   */
  gapRow: "sm" | "md" | "lg" | "xl" | "xxl" | "none";
};
