= Building
:sourcedir: ../

In this chapter we will learn how to set up transpilation of Typescript code - both client- and server-side - to JavaScript.

== Install

=== Types

Install types needed to configure the build system:

[source, Terminal]
----
npm install --save-dev @types/node
----


Install types needed to work with Enonic Core API:
[source, Terminal]
----
npm install --save-dev @enonic-types/core @enonic-types/lib-content @enonic-types/lib-portal @enonic-types/global @enonic-types/lib-context @enonic-types/lib-auth @enonic-types/lib-event @enonic-types/lib-common @enonic-types/lib-repo @enonic-types/lib-websocket @enonic-types/lib-node @enonic-types/lib-i18n @enonic-types/lib-task @enonic-types/lib-io @enonic-types/lib-project @enonic-types/lib-mail @enonic-types/lib-export @enonic-types/lib-scheduler @enonic-types/lib-admin @enonic-types/lib-cluster @enonic-types/lib-value
----


=== Tools

Install tools required to set up transpilation and bundling of Typescript code:

[source, Terminal]
----
npm install --save-dev typescript tsup @swc/core concurrently
----

* `typescript` will enable support of Typescript language by adding syntax for type declarations and annotations
* `tsup` is a TypeScript bundler powered by esbuild
* `@swc/core` is a TypeScript / JavaScript compiler
* `concurrently` is a tool to run multiple commands concurrently

== Configure

=== File processing

We need a cross-platform way to check if there are any files to build, so here are a couple scripts that do just that:

.tsup/anyAssetFiles.js
[source, JavaScript]
----
include::{sourcedir}tsup/anyAssetFiles.js[]
----

.tsup/anyServerFiles.js
[source, JavaScript]
----
include::{sourcedir}tsup/anyServerFiles.js[]
----

=== package.json

Add the following scripts to the `package.json` file (the first script concurrently executes the other two):

[source, JSON]
----
{
  "scripts": {
    "build": "concurrently -c auto -g --timings npm:build:*",
    "build:assets": "node tsup/anyAssetFiles.js && npx tsup -d build/resources/main/assets || exit 0",
    "build:server": "node tsup/anyServerFiles.js && npx tsup -d build/resources/main || exit 0",
  }
}
----

CAUTION: You will typically NOT publish an Enonic XP project to npm, so it's a good idea to add the following to the package.json file:

[source, JSON]
----
{
  "private": true
}
----

=== TypeScript configuration

Add the following config files to the project:

.tsconfig.json
[source, JSON]
----
include::{sourcedir}tsconfig.json[]
----

.src/main/resources/tsconfig.json
[source, JSON]
----
include::{sourcedir}src/main/resources/tsconfig.json[]
----

.src/main/resources/assets/tsconfig.json
[source, JSON]
----
include::{sourcedir}src/main/resources/assets/tsconfig.json[]
----

=== TSup configuration

Add the following config files to the project:

.tsup.config.ts
[source, Typescript]
----
include::{sourcedir}tsup.config.ts[]
----

.tsup/index.d.ts
[source, Typescript]
----
include::{sourcedir}tsup/index.d.ts[]
----

.tsup/constants.ts
[source, Typescript]
----
include::{sourcedir}tsup/constants.ts[]
----

.tsup/client-asset.ts
[source, Typescript]
----
include::{sourcedir}tsup/client-asset.ts[]
----

.tsup/server.ts
[source, Typescript]
----
include::{sourcedir}tsup/server.ts[]
----

== Gradle configuration

=== Node-gradle plugin

In order for Gradle to be able to run npm scripts, you need to use the node-gradle plugin.

Add the following to the build.gradle file:

.build.gradle
[source, Groovy]
----
plugins {
  id 'com.github.node-gradle.node' version '7.0.2'
}

node {
  // Whether to download and install a specific Node.js version or not
  // If false, it will use the globally installed Node.js
  // If true, it will download node using above parameters
  // Note that npm is bundled with Node.js
  download = true

  // Version of node to download and install (only used if download is true)
  // It will be unpacked in the workDir
  version = '20.12.2'
}
----

=== npmBuild task

Add the following task to the build.gradle file, which will run the npm build script defined in package.json:

.build.gradle
[source, Groovy]
----
tasks.register('npmBuild', NpmTask) {
  args = [
    'run',
    '--silent',
    'build'
  ]
  dependsOn npmInstall
  environment = [
    'FORCE_COLOR': 'true',
    'LOG_LEVEL_FROM_GRADLE': gradle.startParameter.logLevel.toString(),
    'NODE_ENV': project.hasProperty('dev') || project.hasProperty('development') ? 'development' : 'production'
  ]
  inputs.dir 'src/main/resources'
  outputs.dir 'build/resources/main'
}

jar.dependsOn npmBuild
----

=== Clean up jar file

Add the following to the build.gradle file:

.build.gradle
[source, Groovy]
----
tasks.withType(Copy).configureEach {
  includeEmptyDirs = false
}

processResources {
  exclude '**/.gitkeep'
  exclude '**/*.json'
  exclude '**/*.ts'
  exclude '**/*.tsx'
}
----

This will make sure that assembled jar file contains only required assets and none of the original source TypeScript files.
