= Building
:sourcedir: ../

== Install

=== Types

Types useful when configuring the build system:

[source, Terminal]
----
npm install --save-dev @types/node
----


Types useful when programming Enonic XP server-side code:
[source, Terminal]
----
npm install --save-dev @enonic-types/core @enonic-types/lib-content @enonic-types/lib-portal @enonic-types/global @enonic-types/lib-context @enonic-types/lib-auth @enonic-types/lib-event @enonic-types/lib-common @enonic-types/lib-repo @enonic-types/lib-websocket @enonic-types/lib-node @enonic-types/lib-i18n @enonic-types/lib-task @enonic-types/lib-io @enonic-types/lib-project @enonic-types/lib-mail @enonic-types/lib-export @enonic-types/lib-scheduler @enonic-types/lib-admin @enonic-types/lib-cluster @enonic-types/lib-value
----


=== Tools

[source, Terminal]
----
npm install --save-dev @swc/core concurrently tsup typescript
----

== Configure

=== Check if there are any files to build

We need a cross platform way to check if there are any files to build, so here's are a couple scripts that does just that:

.tsup/anyAssetFiles.js
[source, JavaScript]
----
include::{sourcedir}tsup/anyAssetFiles.js[]
----

.tsup/anyServerFiles.js
[source, JavaScript]
----
include::{sourcedir}tsup/anyServerFiles.js[]
----

=== package.json

Add the following scripts to the package.json file:

[source, JSON]
----
{
  "scripts": {
    "build": "concurrently -c auto -g --timings npm:build:*",
    "build:assets": "node tsup/anyAssetFiles.js && npx tsup -d build/resources/main/assets || exit 0",
    "build:server": "node tsup/anyServerFiles.js && npx tsup -d build/resources/main || exit 0",
  }
}
----

CAUTION: You will typically NOT publish an Enonic XP project to npm, so it's a good idea to add the following to the package.json file:

[source, JSON]
----
{
  "private": true
}
----

=== TypeScript configuration

Add the following files to the project:

.tsconfig.json
[source, JSON]
----
include::{sourcedir}tsconfig.json[]
----

.src/main/resources/tsconfig.json
[source, JSON]
----
include::{sourcedir}src/main/resources/tsconfig.json[]
----

.src/main/resources/assets/tsconfig.json
[source, JSON]
----
include::{sourcedir}src/main/resources/assets/tsconfig.json[]
----

=== TSup configuration

Add the following files to the project:

.tsup.config.ts
[source, JSON]
----
include::{sourcedir}tsup.config.ts[]
----

.tsup/index.d.ts
[source, JSON]
----
include::{sourcedir}tsup/index.d.ts[]
----

.tsup/constants.ts
[source, JSON]
----
include::{sourcedir}tsup/constants.ts[]
----

.tsup/client-asset.ts
[source, JSON]
----
include::{sourcedir}tsup/client-asset.ts[]
----

.tsup/server.ts
[source, JSON]
----
include::{sourcedir}tsup/server.ts[]
----

== Gradle configuration

=== Node-gradle plugin

In order for gradle to be able to run npm scripts, you need to use the node-gradle plugin.

Add the following to the build.gradle file:

.build.gradle
[source, Groovy]
----
plugins {
  id 'com.github.node-gradle.node' version '7.0.2'
}

node {
  // Whether to download and install a specific Node.js version or not
  // If false, it will use the globally installed Node.js
  // If true, it will download node using above parameters
  // Note that npm is bundled with Node.js
  download = true

  // Version of node to download and install (only used if download is true)
  // It will be unpacked in the workDir
  version = '20.12.2'
}
----

=== npmBuild task

Add the following task to the build.gradle file:

.build.gradle
[source, Groovy]
----
tasks.register('npmBuild', NpmTask) {
  args = [
    'run',
    '--silent',
    'build'
  ]
  dependsOn npmInstall
  environment = [
    'FORCE_COLOR': 'true',
    'LOG_LEVEL_FROM_GRADLE': gradle.startParameter.logLevel.toString(),
    'NODE_ENV': project.hasProperty('dev') || project.hasProperty('development') ? 'development' : 'production'
  ]
  inputs.dir 'src/main/resources'
  outputs.dir 'build/resources/main'
}

jar.dependsOn npmBuild
----

=== Avoid source files in the build folder and jar file

Add the following to the build.gradle file:

.build.gradle
[source, Groovy]
----
tasks.withType(Copy).configureEach {
  includeEmptyDirs = false
}

processResources {
	exclude '**/.gitkeep'
  exclude '**/*.json'
	exclude '**/*.ts'
	exclude '**/*.tsx'
}
----
