= Using TypeScript
:toc: right

This tutorial explains the steps involved in adapting your Enonic app to a best-practice TypeScript build setup - matching that of the https://market.enonic.com/vendors/enonic/ts-starter[TypeScript starter]

TIP: Starting a new project? Get all the good stuff explained in this tutorial by running `enonic project create -r starter-ts`.

== Introduction

This tutorial is aimed at existing Enonic projects, based on JavaScript, or using an older TypeScript setup.

Most projects start with a simple setup and then grow in complexity as more and more features are added. TypeScript can help keep your codebase clean and maintainable.

The tutorial covers:

* Essential <<concepts#, concepts>>
* Setting up the <<build#,Build system>>
* How to enable <<check#,Type checking>>
* Activating <<lint#,Linting>>
* Preparing for <<test#,Testing>>

For some actual TypeScript code examples, check out the https://developer.enonic.com/docs/tsup-starter[Tsup] documentation.

TIP: If you want to learn more about writing tests in TypeScript, you can check out the https://developer.enonic.com/docs/testing-with-jest-and-mock-xp[Testing with Jest and Mock XP] tutorial.
