= Testing
:sourcedir: ../

If you are writing Typescript code, chances are you want to write tests for that code, and you want to write them in Typescript. Here's how to configure test runs in your application. In our example we will configure Jest, a JavaScript testing framework designed to ensure correctness of your JavaScript codebase.

== Install

[source, Terminal]
----
npm install --save-dev jest-environment-jsdom ts-node ts-jest
----


== Configure

=== Jest

In our example we will configure processing of both client-side and server-side Typescript code.

Create a file called jest.config.js in the root of the project with the following content:

[source, TypeScript]
----
include::{sourcedir}jest.config.ts[]
----

With this config Jest will find and execute test files in the 'src/jest/client' and 'src/jest/server' folders called `*.test.ts` (or `.tsx`) or `*.spec.ts` (or `.tsx`).

Set up `src/jest` folder structure with thess files inside:

.src/jest/client/tsconfig.json
[source, JSON]
----
include::{sourcedir}src/jest/client/tsconfig.json[]
----

.src/jest/server/global.d.ts
[source, TypeScript]
----
include::{sourcedir}src/jest/server/global.d.ts[]
----

This Jest setupFile is used to mock the XP Framework <<concepts/globals#,Globals>> into the server-side test environment:

.src/jest/server/setupFile.ts
[source, TypeScript]
----
include::{sourcedir}src/jest/server/setupFile.ts[]
----

.src/jest/server/tsconfig.json
[source, JSON]
----
include::{sourcedir}src/jest/server/tsconfig.json[]
----

=== package.json

Add the following scripts to the package.json file:

[source, JSON]
----
{
  "scripts": {
    "cov": "jest --no-cache --coverage",
    "test": "jest --no-cache"
  }
}
----

`test` command starts execution of tests. `cov` command does exactly the same, but also generates coverage report.

=== build.gradle

Add the following task to the build.gradle file:

.build.gradle
[source, Groovy]
----
tasks.register('npmTest', NpmTask) {
	args = [
		'run',
		'test'
	]
	dependsOn npmInstall
	environment = [
		'FORCE_COLOR': 'true',
	]
  inputs.dir 'src/jest'
  outputs.dir 'coverage'
}

test.dependsOn npmTest
----

With this setup tests will be executed on every build, but you can also run them separately with the following command:

[source, Terminal]
----
./gradlew test
----

== Additional reading

If you want to learn more about writing tests in TypeScript, you can check out the https://developer.enonic.com/docs/testing-with-jest-and-mock-xp[Testing with Jest and Mock-XP] tutorial.

== Navigation

In the next chapter we will learn how to use the <<result#,result>> to create future projects with everything already setup.
