= Testing
:sourcedir: ../

If you are writing Typescript code, chances are you want to write tests for that code, and you want to write them in Typescript. Here's how to configure test runs in your application. In our example we will configure Jest, a JavaScript testing framework designed to ensure correctness of your JavaScript codebase.

== Install

[source, Terminal]
----
npm install --save-dev jest-environment-jsdom ts-node ts-jest
----


== Configure

=== Jest

In our example we will configure processing of server-side Typescript code, but you can similarly configure client-side code.

Create a file called jest.config.js in the root of the project with the following content:

[source, TypeScript]
----
include::{sourcedir}jest.config.ts[]
----

With this config Jest will find and execute test files in the 'src/main/resources' folder called `*.test.ts` (or `.tsx`) or `*.spec.ts` (or `.tsx`).

Set up `src/jest/server` folder structure and create two files inside:

[source, TypeScript]
----
include::{sourcedir}src/jest/server/global.d.ts[]
----

[source, TypeScript]
----
include::{sourcedir}src/jest/server/setupFile.ts[]
----

=== package.json

Add the following scripts to the package.json file:

[source, JSON]
----
{
  "scripts": {
    "cov": "jest --no-cache --coverage",
    "test": "jest --no-cache"
  }
}
----

`test` command starts execution of tests. `cov` command does exactly the same, but also generates coverage report.

=== build.gradle

Add the following task to the build.gradle file:

.build.gradle
[source, Groovy]
----
tasks.register('npmTest', NpmTask) {
	args = [
		'run',
		'test'
	]
	dependsOn npmInstall
	environment = [
		'FORCE_COLOR': 'true',
	]
  inputs.dir 'src/jest'
  outputs.dir 'coverage'
}

test.dependsOn npmTest
----

With this setup tests will be executed on every build, but you can also run them separately with the following command:

[source, Terminal]
----
./gradlew test
----
