// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksAccordion = {
  /**
   * Title
   */
  title?: string;

  /**
   * Theme
   */
  theme?: string;

  /**
   * Accordion element
   */
  items: Array<{
    /**
     * Title
     */
    title: string;

    /**
     * Text
     */
    text: string;
  }>;
};
