// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksQuote = {
  /**
   * Text
   */
  text: string;

  /**
   * Name of person quoted
   */
  author?: string;

  /**
   * Author Image
   */
  imageId?: string;

  /**
   * Title
   */
  publicationTitle?: string;

  /**
   * Url
   */
  publicationUrl?: string;
};
