// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Default = {
  /**
   * Theme color
   */
  themeColorClass: "theme-white" | "theme-turquiose-light" | "theme-green";

  /**
   * Show With Aside
   */
  showWithAside: boolean;
}
