// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Media = {
  /**
   * Image
   */
  media:
    | {
        /**
         * Selected
         */
        _selected: "withAltText";

        /**
         * Normal image
         */
        withAltText: {
          /**
           * Image
           */
          image: string;

          /**
           * Description of the image for visually impaired users (alt text)
           */
          altText: string;

          /**
           * Caption
           */
          caption?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "withoutAltText";

        /**
         * Decorative image
         */
        withoutAltText: {
          /**
           * Image
           */
          image: string;

          /**
           * Caption
           */
          caption?: string;
        };
      }
    | {
        /**
         * Selected
         */
        _selected: "none";

        /**
         * No image
         */
        none: Record<string, unknown>;
      };
}
